import type { Prisma } from '@/generated/prisma/client';
import { db, type Tx } from '@/lib/db';
import { sendEmail } from '@/lib/email';
import { DomainError } from '@/lib/errors';
import { enqueueEvent } from '@/lib/outbox';
import { maskEmail } from '@/lib/phone';
import { formatPriceText } from '@/lib/price-format';
import { env } from '@/lib/env';
import { add, money, multiply, serialize, subtract, sum, zero, type Money } from '@/lib/money';
import { logger } from '@/lib/logger';
import { renderOrderReceivedEmail } from '@/emails/order-received';
import * as inventory from '@/modules/inventory/service';
import { recordSend, wasSent } from '@/modules/notifications/service';
import { getPaymentProvider } from '@/modules/payments/registry';
import type { PaymentProviderId, PlacementPlan } from '@/modules/payments/provider';
import { recordPayment } from '@/modules/payments/service';
import { formatEta, type DeliveryOption } from '@/modules/shipping/quote';
import type { SellableVariant } from '@/modules/catalog/service';
import { loadCustomerExtras } from './customer-extras';
import * as repo from './repository';
import { STATUS_LABEL, timelineFor, type OrderStatus } from './timeline';
import {
  deriveTrackingToken,
  factorMatches,
  hashTrackingToken,
  isTrackingToken,
  normalizeFactor,
  safeEqual,
} from './tracking';
import type {
  CustomerOrderView,
  MinimalOrderView,
  PlacedOrder,
  ShippingAddressSnapshot,
  ShippingMethodSnapshot,
} from './types';

export { lockPhone } from './repository';

// ---------------------------------------------------------------------------------------------
// Placing an order
// ---------------------------------------------------------------------------------------------

export type OrderChannelId = 'web' | 'manual' | 'facebook' | 'instagram' | 'whatsapp' | 'store';

export interface PlaceOrderCommand {
  /** Generated by the caller so the tracking token can be derived before the insert. */
  orderId: string;
  /** Where the order came from. Staff typing in a phone order use the channel of the conversation. */
  channel?: OrderChannelId;
  /** The staff member (staff_members.id) who typed the order in; null for a web order. */
  createdBy?: string | null;
  userId: string | null;
  contact: { name: string; phone: string; email: string | null };
  address: ShippingAddressSnapshot;
  addressHash: string;
  ipHash: string | null;
  customerNote: string | null;
  /** Prices and costs read from the database inside this transaction (INV-M3, INV-O5). */
  lines: ReadonlyArray<{ variant: SellableVariant; quantity: number }>;
  currency: string;
  delivery: { zoneId: string; zoneName: string; option: DeliveryOption };
  providerId: PaymentProviderId;
  plan: PlacementPlan;
  risk: { score: number; flags: string[] };
  discountMinor?: bigint;
  discountCodes?: string[];
  lineDiscounts?: ReadonlyMap<string, bigint>;
}

export interface OrderTotals {
  subtotal: Money;
  discount: Money;
  shipping: Money;
  total: Money;
}

/** Subtotal, delivery and total from database prices; the one place order arithmetic happens. */
export function totalsFor(
  lines: ReadonlyArray<{
    variant: Pick<SellableVariant, 'priceMinor' | 'currency'>;
    quantity: number;
  }>,
  currency: string,
  shipping: Money,
  discount: Money = zero(currency),
): OrderTotals {
  const subtotal = sum(
    lines.map((line) =>
      multiply(money(line.variant.priceMinor, line.variant.currency), line.quantity),
    ),
    currency,
  );
  const effectiveDiscount = discount.minor > subtotal.minor ? subtotal : discount;
  const total = add(subtract(subtotal, effectiveDiscount), shipping);
  return { subtotal, discount: effectiveDiscount, shipping, total };
}

/**
 * Writes a new order, in the caller's transaction (checkout owns the transaction, the idempotency
 * claim and the cart). In order: stock leaves through the inventory service (the atomic
 * conditional update that makes overselling impossible, INV-S2), the order and its lines are
 * written with price AND cost snapshots (INV-O5), then the timeline row, the payment record and the
 * outbox event. The order is born `placed` and waits for a staff member to verify it: nothing here
 * can confirm, and nothing ever cancels it (ADR-015, INV-O1, INV-O2).
 */
export async function createPlaced(tx: Tx, cmd: PlaceOrderCommand): Promise<PlacedOrder> {
  const discount = money(cmd.discountMinor ?? 0n, cmd.currency);
  const totals = totalsFor(cmd.lines, cmd.currency, cmd.delivery.option.charge, discount);

  let effectTags: string[] = [];
  if (cmd.plan.stock === 'commit_on_place') {
    const effect = await inventory.sell(tx, {
      referenceType: 'order',
      referenceId: cmd.orderId,
      lines: cmd.lines.map((line) => ({ variantId: line.variant.id, quantity: line.quantity })),
    });
    effectTags = effect.tags;
  } else {
    const effect = await inventory.reserve(tx, {
      referenceType: 'order',
      referenceId: cmd.orderId,
      lines: cmd.lines.map((line) => ({ variantId: line.variant.id, quantity: line.quantity })),
    });
    effectTags = effect.tags;
  }

  const option = cmd.delivery.option;
  const method: ShippingMethodSnapshot = {
    zoneId: cmd.delivery.zoneId,
    zoneName: cmd.delivery.zoneName,
    rateId: option.rateId,
    rateName: option.name,
    listedMinor: option.listed.minor.toString(),
    chargedMinor: option.charge.minor.toString(),
    freeOverMinor: option.freeOver ? option.freeOver.minor.toString() : null,
    free: option.free,
    minDays: option.minDays,
    maxDays: option.maxDays,
  };

  const created = await repo.insertOrder(tx, {
    id: cmd.orderId,
    userId: cmd.userId,
    email: cmd.contact.email,
    phone: cmd.contact.phone,
    customerName: cmd.contact.name,
    status: 'placed',
    paymentStatus: cmd.plan.orderPaymentStatus,
    fulfillmentStatus: 'unfulfilled',
    channel: cmd.channel ?? 'web',
    createdBy: cmd.createdBy ?? null,
    currency: cmd.currency,
    subtotalMinor: totals.subtotal.minor,
    discountMinor: totals.discount.minor,
    shippingChargedMinor: totals.shipping.minor,
    taxMinor: 0n,
    totalMinor: totals.total.minor,
    shippingAddress: cmd.address as unknown as Prisma.InputJsonValue,
    shippingMethod: method as unknown as Prisma.InputJsonValue,
    discountCodes: cmd.discountCodes ?? [],
    customerNote: cmd.customerNote,
    riskScore: cmd.risk.score,
    riskFlags: cmd.risk.flags,
    trackingTokenHash: hashTrackingToken(deriveTrackingToken(cmd.orderId)),
    addressHash: cmd.addressHash,
    ipHash: cmd.ipHash,
  });

  await repo.insertItems(
    tx,
    cmd.lines.map(({ variant, quantity }) => {
      const unit = money(variant.priceMinor, variant.currency);
      const lineSubtotal = multiply(unit, quantity).minor;
      const lineDiscount = cmd.lineDiscounts?.get(variant.id) ?? 0n;
      const totalMinor = lineSubtotal - lineDiscount;
      return {
        orderId: cmd.orderId,
        variantId: variant.id,
        productId: variant.productId,
        titleSnapshot: variant.productTitle,
        variantTitleSnapshot: variant.optionsLabel,
        skuSnapshot: variant.sku,
        optionsSnapshot: variant.options as unknown as Prisma.InputJsonValue,
        imageSnapshot: variant.image?.url ?? null,
        unitPriceMinor: unit.minor,
        compareAtMinor: variant.compareAtMinor,
        unitCostMinor: variant.avgCostMinor,
        quantity,
        discountMinor: lineDiscount,
        taxMinor: 0n,
        totalMinor: totalMinor < 0n ? 0n : totalMinor,
      };
    }),
  );

  await repo.insertEvent(tx, {
    orderId: cmd.orderId,
    type: 'placed',
    toStatus: 'placed',
    actorId: cmd.createdBy ?? null,
    payload: {
      channel: cmd.channel ?? 'web',
      paymentMethod: cmd.providerId,
      itemCount: cmd.lines.length,
    },
  });
  await recordPayment(tx, {
    orderId: cmd.orderId,
    providerId: cmd.providerId,
    plan: cmd.plan,
    amount: totals.total,
  });
  await enqueueEvent(tx, {
    type: 'order.placed',
    aggregateType: 'order',
    aggregateId: cmd.orderId,
    payload: {
      orderId: cmd.orderId,
      paymentMethod: cmd.providerId,
      currency: cmd.currency,
      totalMinor: totals.total.minor.toString(),
      channel: cmd.channel ?? 'web',
    },
  });

  return { orderId: cmd.orderId, orderNumber: created.orderNumber, tags: effectTags };
}

// ---------------------------------------------------------------------------------------------
// Velocity and risk inputs for checkout (INV-O11)
// ---------------------------------------------------------------------------------------------

export const velocitySnapshot = repo.velocityCounts;

/** Active flags on a phone number (fake orders, repeat returns, abuse). */
export async function activeRiskFlags(tx: Tx, phone: string, now: Date = new Date()) {
  return (await repo.activeRiskFlags(tx, phone, now)).map((flag) => flag.type);
}

// ---------------------------------------------------------------------------------------------
// Customer views
// ---------------------------------------------------------------------------------------------

type OrderWithDetail = NonNullable<Awaited<ReturnType<typeof repo.findById>>>;

const PAYMENT_STATUS_VIEW = [
  'unpaid',
  'pending',
  'paid',
  'partially_refunded',
  'refunded',
  'failed',
] as const;

const absoluteImage = (url: string | null): string | null => {
  if (!url) return null;
  return /^https?:\/\//.test(url) ? url : `${env.APP_URL.replace(/\/$/, '')}${url}`;
};

function paymentLabel(order: OrderWithDetail): string {
  const provider = order.payments[0]?.provider;
  if (!provider) return 'Payment';
  try {
    return getPaymentProvider(provider).label;
  } catch {
    return 'Payment';
  }
}

function addressLines(address: ShippingAddressSnapshot): string[] {
  return [
    address.line1,
    address.line2,
    [address.area, address.thana.name].filter(Boolean).join(', '),
    [address.district.name, address.division.name, address.postalCode].filter(Boolean).join(', '),
  ].filter((line): line is string => Boolean(line && line.trim()));
}

export function toCustomerView(order: OrderWithDetail): CustomerOrderView {
  const address = order.shippingAddress as unknown as ShippingAddressSnapshot;
  const method = order.shippingMethod as unknown as ShippingMethodSnapshot;
  const status = order.status as OrderStatus;
  const payment = order.paymentStatus;
  return {
    orderNumber: order.orderNumber,
    firstName: order.customerName.split(' ')[0] || order.customerName,
    status,
    statusLabel: STATUS_LABEL[status],
    timeline: timelineFor(status),
    placedAt: order.placedAt.toISOString(),
    items: order.items.map((item) => ({
      title: item.titleSnapshot,
      variantLabel: item.variantTitleSnapshot,
      quantity: item.quantity,
      unitPrice: serialize(money(item.unitPriceMinor, order.currency)),
      lineTotal: serialize(money(item.totalMinor, order.currency)),
      imageUrl: item.imageSnapshot,
    })),
    subtotal: serialize(money(order.subtotalMinor, order.currency)),
    discount: serialize(money(order.discountMinor, order.currency)),
    shipping: serialize(money(order.shippingChargedMinor, order.currency)),
    total: serialize(money(order.totalMinor, order.currency)),
    address: { name: address.fullName, lines: addressLines(address) },
    delivery: {
      zoneName: method.zoneName,
      rateName: method.rateName,
      eta: formatEta(method.minDays, method.maxDays),
    },
    payment: {
      label: paymentLabel(order),
      status: PAYMENT_STATUS_VIEW.includes(payment) ? payment : 'unpaid',
    },
    emailMasked: order.email ? maskEmail(order.email) : null,
    parcel: null,
    updates: [],
    returns: [],
    returnOffer: null,
  };
}

/** The order page view with the parcel, the dated steps and the return offer filled in. */
async function withExtras(order: OrderWithDetail): Promise<CustomerOrderView> {
  const view = toCustomerView(order);
  const extras = await loadCustomerExtras(order.id, order.status as OrderStatus, order.deliveredAt);
  return { ...view, ...extras };
}

export function toMinimalView(order: OrderWithDetail): MinimalOrderView {
  const status = order.status as OrderStatus;
  return {
    orderNumber: order.orderNumber,
    status,
    statusLabel: STATUS_LABEL[status],
    timeline: timelineFor(status),
    placedAt: order.placedAt.toISOString(),
  };
}

/** The order a tracking token belongs to, or null. The stored value is compared in constant time. */
async function orderForToken(token: string): Promise<OrderWithDetail | null> {
  if (!isTrackingToken(token)) return null;
  const hash = hashTrackingToken(token);
  const order = await repo.findByTrackingHash(db, hash);
  return order && safeEqual(order.trackingTokenHash, hash) ? order : null;
}

export async function orderIdForToken(token: string): Promise<string | null> {
  return (await orderForToken(token))?.id ?? null;
}

/**
 * The full order for a tracking token, when `unlocked` says this visitor already showed the second
 * factor (a valid proof cookie). Returns null for an unknown token and also when not unlocked
 * (the page then asks for the phone or email, the same for both cases).
 */
export async function viewForToken(
  token: string,
  isUnlocked: (orderId: string) => boolean,
): Promise<CustomerOrderView | null> {
  const order = await orderForToken(token);
  if (!order || !isUnlocked(order.id)) return null;
  return withExtras(order);
}

/**
 * Checks the phone or email a customer typed against the order behind a tracking token. Returns the
 * order id on a match and null on anything else (unknown token, wrong factor, malformed factor):
 * the caller shows one generic message for all of them.
 */
export async function verifyTokenFactor(token: string, factorText: string): Promise<string | null> {
  const factor = normalizeFactor(factorText);
  const order = await orderForToken(token);
  // Always compare, so a wrong token costs about as much as a wrong factor.
  const probe = { phone: order?.phone ?? '+8800000000000', email: order?.email ?? null };
  const matches = factor ? factorMatches(factor, probe) : false;
  return order && matches ? order.id : null;
}

/** Order number plus phone or email: the status only, never items or address (INV-O10). */
export async function lookupMinimal(
  orderNumber: string,
  factorText: string,
): Promise<MinimalOrderView | null> {
  const factor = normalizeFactor(factorText);
  const order = await repo.findByNumber(db, orderNumber.trim().toUpperCase());
  const probe = { phone: order?.phone ?? '+8800000000000', email: order?.email ?? null };
  const matches = factor ? factorMatches(factor, probe) : false;
  return order && matches ? toMinimalView(order) : null;
}

/** The order the buyer just placed, for the confirmation page of the browser that placed it. */
export async function customerViewById(orderId: string): Promise<CustomerOrderView | null> {
  const order = await repo.findById(db, orderId);
  return order ? withExtras(order) : null;
}

export const trackingTokenFor = deriveTrackingToken;

// ---------------------------------------------------------------------------------------------
// "Order received" email (from the order.placed event)
// ---------------------------------------------------------------------------------------------

const RECEIVED_TEMPLATE = 'order_received';

/**
 * Sends the "we have your order" email once. Runs in a background job after the order committed
 * (INV-E1). A retried job finds the send log and does nothing (INV-E2); an order without an email
 * address is skipped and logged as such.
 */
export async function sendOrderReceivedEmail(orderId: string): Promise<'sent' | 'skipped'> {
  const order = await repo.findById(db, orderId);
  if (!order) throw new DomainError('NOT_FOUND', 'Order not found');
  if (await wasSent(RECEIVED_TEMPLATE, 'order', orderId)) return 'skipped';
  if (!order.email) {
    await recordSend({
      channel: 'email',
      template: RECEIVED_TEMPLATE,
      toMasked: 'no email given',
      status: 'skipped',
      relatedType: 'order',
      relatedId: orderId,
    });
    return 'skipped';
  }

  const view = toCustomerView(order);
  const origin = env.APP_URL.replace(/\/$/, '');
  const rendered = await renderOrderReceivedEmail({
    firstName: view.firstName,
    orderNumber: view.orderNumber,
    lines: view.items.map((item) => ({
      title: item.title,
      variantLabel: item.variantLabel,
      quantity: item.quantity,
      unitPrice: formatPriceText(money(BigInt(item.unitPrice.minor), item.unitPrice.currency)),
      lineTotal: formatPriceText(money(BigInt(item.lineTotal.minor), item.lineTotal.currency)),
      imageUrl: absoluteImage(item.imageUrl),
    })),
    subtotal: formatPriceText(money(BigInt(view.subtotal.minor), view.subtotal.currency)),
    shipping:
      BigInt(view.shipping.minor) === 0n
        ? 'Complimentary'
        : formatPriceText(money(BigInt(view.shipping.minor), view.shipping.currency)),
    total: formatPriceText(money(BigInt(view.total.minor), view.total.currency)),
    addressLines: [view.address.name, ...view.address.lines],
    paymentLabel: view.payment.label,
    trackUrl: `${origin}/track/${deriveTrackingToken(orderId)}`,
  });

  try {
    await sendEmail({ to: order.email, ...rendered });
  } catch (error) {
    await recordSend({
      channel: 'email',
      template: RECEIVED_TEMPLATE,
      toMasked: maskEmail(order.email),
      status: 'failed',
      error: error instanceof Error ? error.message : 'send failed',
      relatedType: 'order',
      relatedId: orderId,
    });
    logger.error({ err: error, orderId }, 'order received email failed');
    // Re-thrown so the job retries; the log keeps every failed attempt.
    throw error;
  }
  await recordSend({
    channel: 'email',
    template: RECEIVED_TEMPLATE,
    toMasked: maskEmail(order.email),
    status: 'sent',
    relatedType: 'order',
    relatedId: orderId,
  });
  return 'sent';
}
